import { ReactNode } from 'react'
import { Nav } from '../components/Nav'
import '../styles/global.css'

import { Unica_One, Inter } from '@next/font/google'

const unicaOne = Unica_One({ weight: '400', subsets: ['latin'], variable: '--unica-one-font' })
const inter = Inter({ weight: '400', subsets: ['latin'], variable: '--inter-font' })

type RootLayoutProps = { children: ReactNode }
export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang="en" className={` ${inter.variable} ${unicaOne.variable}`}>
			<head>
				<title>Sebastian Garces</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body className="flex h-full min-h-screen flex-col bg-bg-color">
				<main className="flex w-full grow justify-center py-40 text-text-color">
					<div className="flex w-[1080px]">
						<Nav />
						<div className="h-full w-full">{children}</div>
					</div>
				</main>
			</body>
		</html>
	)
}
